// This source code is a part of Project Violet.
// Copyright (C) 2020. rollrat. Licensed under the MIT License.

import 'package:communityexplorer/component/interface.dart';
import 'package:communityexplorer/other/html/parser.dart';

class ArcaLiveData extends BoardData {
  static const boards = {
    '라스트오리진': '/b/lastorigin',
    '카운터사이드': '/b/counterside',
    '걸 카페 건': '/b/girlcafe',
    '붕괴3rd': '/b/hk3rd',
    '툴리우스': '/b/tullius',
    '데스티니 차일드': '/b/destinychild',
    '미치쿠사야/동인음성': '/b/momoirocode',
    '사회': '/b/society',
    'SMpeople': '/b/smpeople',
    '라이브 온도계': '/b/thermometer',
    '백묘': '/b/baekmyo',
    '프린세스 커넥트 Re:Dive': '/b/prcn',
    '몬무스': '/b/monmusu',
    '유즈소프트': '/b/yuzusoft',
    '초대형소녀': '/b/giantess2',
    '커스텀 메이드': '/b/com3d2',
    '텍스트게임': '/b/textgame',
    '라오창작물검색용': '/b/supernerimk2',
    '도시·지리': '/b/city',
    'DMM게임즈': '/b/dmmgames',
    '대마인RPG': '/b/taimaninrpg',
    '원주민 보호구역': '/b/talk',
    '얀데레': '/b/yandere',
    '나무게임': '/b/namugame',
    '창작소설': '/b/writingnovel',
    '트릭컬': '/b/trickcal',
    '코이카츠': '/b/koikatsu',
    '성인 애니메이션': '/b/anime18',
    '유이챈러스': '/b/hobby',
    '아자젤': '/b/azazel',
    '유머/이슈': '/b/issue',
    '물리': '/b/physics',
    '가디언 테일즈': '/b/guardiantales',
    '명일방주': '/b/hypergryph',
    'LonaRPG': '/b/lonarpg',
    '게임': '/b/game',
    '벽람항로': '/b/azurlane',
    '성소수자': '/b/lgbt',
    '쯔꾸르': '/b/rpgmaker',
    '성인게임': '/b/yagame',
    '오네쇼타': '/b/oneshota',
    '컨트리볼': '/b/countryball',
    '랜덤채팅': '/b/random',
    '원신': '/b/genshin',
    '채널 차단 문의': '/b/whyiblocked',
    '동방프로젝트': '/b/touhou',
    '/19': '/b/187788',
    '컴퓨터공학': '/b/programmers',
    '요리': '/b/cook',
    '제5인격': '/b/identityv',
    '건의': '/b/request',
    '군사': '/b/military815',
    '공지': '/b/notice',
    '일본문화': '/b/nihonbunka',
    '소녀전선2': '/b/girlsfrontline2',
    '창소챈러스': '/b/wners',
    '수수방관 그림': '/b/grim',
    'TS물': '/b/tsfiction',
    '생물': '/b/organism',
    '뱅드림': '/b/bangdream',
    '노래추천': '/b/song',
    '창작 음악': '/b/composers',
    '포토그래피': '/b/photography',
    '에로게 번역': '/b/ytranslation',
    '님페트': '/b/nymphet',
    '스캇 오버그': '/b/scottoberg',
    '후타나리': '/b/futanari',
    '신고 게시판': '/b/report',
    '수인 쇼타': '/b/furryshota',
    '라오 일섭': '/b/jplasori',
    '아카 리프레셔': '/b/namurefresher',
    '카툰연재': '/b/cartoonserialization',
    '미니기기': '/b/smartphone',
    '리듬 게임': '/b/mgamm',
    '밀리시타': '/b/mltd',
    '항공우주': '/b/aerospace',
    '국내야구': '/b/koreabaseball',
    '이사': '/b/2424',
    'Aqours': '/b/aqours',
    '허니셀렉트': '/b/honeyselect',
    '워썬더': '/b/warthunder',
    '다키마쿠라': '/b/dakimakura',
    '대전세종충남': '/b/djsjcn',
    '게이격리소': '/b/gayghetto',
    '아이돌/연예인': '/b/celeb',
    '맛집': '/b/famousrestaurant',
    'LOL': '/b/1557',
    '항공': '/b/airplane',
    '오나홀': '/b/onahole',
    '고전 음악': '/b/muzyka24601',
    '미연시': '/b/dcmys',
    '사회 채널 관리': '/b/soc1etyadmin',
    'T 14 미호': '/b/t14miho',
    'UK록': '/b/unitedkingdomrocks',
    '버추얼 유튜버': '/b/vtubers',
    '영원한7일의도시': '/b/07do',
    '하무망': '/b/hammumang',
    '채널 커뮤니티': '/b/channel',
    '여행관광': '/b/trips',
    '주식': '/b/stock',
    '광주전남': '/b/gwangju',
    '블루 아카이브': '/b/bluearchive',
    '백합': '/b/lily',
    '유즈키 유카리': '/b/yuzuyuka',
    '에픽세븐': '/b/epic7',
    '수간': '/b/animallove',
    '도지챈 관리': '/b/dojigwanri',
    '랑그릿사': '/b/langrisser',
    '이사2': '/b/242424',
    '재난재해': '/b/catastrophe',
    'MMD': '/b/mikumikudance',
    '핫딜': '/b/hotdeal',
    '인외 마스코트': '/b/mascot',
    '촉진주의': '/b/speedlovers',
    '베이블레이드': '/b/beyblade',
    '언어/언어학': '/b/chomsky',
    '닌텐도': '/b/nintendocoltd',
    '와타모테': '/b/watamote',
    '음악 music': '/b/trunkmuzikthree',
    '속옷': '/b/underwear',
    '동인음성': '/b/donginvoice',
    '퍼니싱': '/b/punigray',
    '모험가': '/b/mogall',
    '와타텐': '/b/wataten',
    '카구야': '/b/kaguya',
    '화폐': '/b/currency',
    'MCU': '/b/iamironman',
    '프론트엔드': '/b/frontend',
    '2D 저장소': '/b/manganumber',
    '케모노': '/b/anthromorph',
    '대체역사 갤러리': '/b/alterhistory',
    '오토코노코': '/b/otokonoko',
    'NTR': '/b/netotate',
    'Duolingo': '/b/duoling0',
    '박도리': '/b/bakdori',
    '점갤저장소': '/b/jumper',
    '충북': '/b/cheongju2',
    '시라사기 치사토': '/b/chisato',
    '채널 관리 공지': '/b/opnotice',
    '야생소녀': '/b/yasang',
    '페이트그랜드오더': '/b/fatego',
    '문예 창작': '/b/poemnovel',
    '프리코네 클랜전': '/b/priconne',
    '바둑갤러리': '/b/badukgallery',
    '보카로': '/b/vocalo',
    'Manjuu': '/b/manjuugame',
    '걸즈 앤 판처': '/b/girlsundpanzer',
    '가면라이더': '/b/ridertime',
    '겨드랑이': '/b/armpit',
    '메이플스토리 리부트': '/b/reboot',
    '영웅전희': '/b/eiyuwwx',
    '일루전 커넥트': '/b/illucone',
    '뽀끄루 대마왕': '/b/faucre',
    '미국주식': '/b/magastock',
    '오드로이드': '/b/odroid',
    'BBW': '/b/bbwlove',
    '프리코네 아레나': '/b/pricone',
    '유로트럭2': '/b/ets2',
    '증권': '/b/certiflcate',
    '단간론파 저장소': '/b/dgrp',
    '캬루': '/b/kiruya',
    '에르제베트': '/b/elezebet',
    '나나오아카리': '/b/nanawo',
    '한그오 정보': '/b/fategoinfo',
    '클로저스': '/b/closers',
    '근육녀': '/b/musclegirl',
    '노래 가사 번역': '/b/lyricstranslation',
    '일문챈 관리': '/b/nihonbunkakanri',
    '각종 보드게임': '/b/boardgames',
    '메이플 스토리': '/b/maple',
    '판도학': '/b/mapporn',
    '시로네코프로젝트': '/b/shironeko',
    '개신교': '/b/protestantism',
    '아마미 하루카': '/b/amami',
    '샤니마스': '/b/shinycolors',
    '메티스': '/b/metis',
    '리뷰': '/b/reviews',
    '외부 광고': '/b/advertisements',
    '레베럽': '/b/reverubproject',
    '막고라': '/b/makgora',
    '피파 게임': '/b/fifa111',
    '타이타닉': '/b/titanic',
    '월드오브탱크': '/b/tank',
    '아틀리에': '/b/atelier',
    '카연챈러스': '/b/cartoonuser',
    '지옥': '/b/hell',
    '가톨릭': '/b/catholicchannel',
    '익명 채팅': '/b/anonymouschat',
    '워해머': '/b/warhammer',
    '전라북도': '/b/jeollabukdo',
    '만화 연재': '/b/cartoondraw',
    '중세게임': '/b/aoegame',
    '밀리터리 씹덕': '/b/militaryanime',
    '해외주식': '/b/fcstock',
    '닥터': '/b/doctor',
    '천문/기상/지구': '/b/astrometeogeo',
    '방주지령': '/b/arkorder',
    '얼티밋스쿨': '/b/ultimateschool',
    '제이위키': '/b/jwiki',
    '합성물': '/b/hapsung',
    '웹툰': '/b/webtoon',
    'IA': '/b/iaariaontheplanetes',
    '고전 애니': '/b/rumic',
    '유머': '/b/humor',
    'Software': '/b/sosome1111',
    '계약': '/b/contract',
    '역사': '/b/historystorage',
    'FPS': '/b/fpsgame',
    '킹스레이드': '/b/kingsraid',
    '앨리스 기어': '/b/alicegearaegis',
    '홀로라이브': '/b/hololive',
    '라오의방주': '/b/smartjoy',
    '아이즈원': '/b/izone',
    '브라운더스트': '/b/browndust',
    '파이썬': '/b/python',
    '에어소프트': '/b/airsoft',
    '천년전쟁아이기스': '/b/aigisinfo',
    '아카이브 백업': '/b/akaback',
    '수능과 대입논술': '/b/suneungnonsul',
    '이브': '/b/originalsineve',
    '장르소설': '/b/novelchannel',
    'NO무현': '/b/nomugudock',
    'FC바이에른뮌헨': '/b/fcbayern',
    '동인지': '/b/doujinshi',
    '망가': '/b/manga',
    '러블리너스': '/b/lovelinuschannel',
    'TRPG/ORPG': '/b/trpg',
    '(구)자동차': '/b/cars',
    '동물의숲': '/b/hatenook',
    'manias': '/b/halfmoon',
    '페이트': '/b/fate',
    '처녀학': '/b/virgin',
    '귀멸의 칼날': '/b/kimetsunoyaiba',
    'DC마이너갤러리': '/b/dcmg',
    '모치다 아리사': '/b/vove',
    '드래곤': '/b/dragonz',
    '해외 축구': '/b/forefoot',
    '뷰티풀군바리': '/b/beautifulmillife',
    '하이퍼그리프': '/b/arkcn',
    '레이시': '/b/wraithy',
    '노바': '/b/nova',
    '클래시오브클랜': '/b/clashofclans',
    '백토': '/b/magicpinkmoonlight',
    '니코니코 동화': '/b/nicovideo',
    '담배': '/b/cigar',
    '생존주의': '/b/survivalism',
    '청공의 칼날': '/b/aozora',
    'T1 LOL': '/b/t1lol',
    '깐프 유즈맵': '/b/wer3chan',
    '심포기어 XD': '/b/symphogearxd',
    '야옹이': '/b/cats',
    '던전앤파이터': '/b/dunfa',
    '맨체스터 유나이티드': '/b/manutd',
    '프리코': '/b/precor',
    '심연의부름': '/b/5coa',
    '고전 게임': '/b/classicgame',
    '자동총기': '/b/automaticgun',
    '미야와키 사쿠라': '/b/sakura',
    '치이 아루엘': '/b/chiiaruel',
    '주시윤': '/b/countersideouch',
    'PSO2': '/b/pso2',
    '장갑 페티쉬': '/b/gloves1',
    '월드플리퍼': '/b/worldflipper',
    '국내 축구': '/b/football',
    '안구정화': '/b/eyebleach',
    '이지투온': '/b/ez2on',
    '임페라토르 롬': '/b/roma',
    '해외 영화': '/b/moviekinofilm',
    '타마린느': '/b/epic7tactic',
    '킬미 베이비': '/b/killmebaby',
    '컴퓨터 본체': '/b/comh',
    '프리큐어 시즌2': '/b/precure',
    '쓰르라미': '/b/higurashi',
    '캣파이트': '/b/catfight',
    '레전드오브룬테라': '/b/runeterra',
    'NiziU': '/b/nizi',
    '스타마인': '/b/starmine',
    '아틀리에 시리즈': '/b/atelierseries',
    '아케아': '/b/arcaea123',
    '라빗츠': '/b/rabits',
    '운디네': '/b/undine',
    '파이널판타지14': '/b/ff14',
    'AL팬텀': '/b/alphantom',
    '고시와 전문직': '/b/professional',
    '렌탈여친': '/b/kanokari',
    '텍스트번역': '/b/transtext',
    '사이퍼즈': '/b/cyphers',
    '대항해시대': '/b/meohang',
    '스마트조이': '/b/smjoy',
    '댄싱시티': '/b/dancingcity',
    '토트넘 핫스퍼': '/b/tottenham',
    '청주/충북 채널': '/b/cheongjucb',
    'T1': '/b/t1esports',
    '짬뽕': '/b/jjambbong',
    '나나히라': '/b/nanahira',
    'MGTOW': '/b/mgtow',
    '최예나': '/b/chaeyaena',
    '권은비': '/b/kwoneunbi',
    '조유리': '/b/joyuri',
    '안유진': '/b/anyujin',
    'TK': '/b/taekyoung',
    '패뷸러스플러스': '/b/fabulous',
    '메이드인어비스': '/b/magelgoobd',
    '논리 퍼즐': '/b/logicpuzzle',
    '앙상블스타즈': '/b/ensemblestars',
    '대학 생활': '/b/university',
    '슈퍼로봇 2': '/b/srwx',
    '수도권': '/b/sudoku',
    '자지': '/b/penis',
    '메모리아 프레제': '/b/dmm1',
    '섀도우버스': '/b/shadowverse',
    '로스트 아크': '/b/lostark1',
    '컴퓨터': '/b/pcrace',
    '도타2Dota2': '/b/dota',
    '아카 공식 잡담': '/b/arcaliveofficials',
    'JDM': '/b/jdmchannel',
    'VR챗': '/b/vrchat',
    '슈팅 게임': '/b/shooting',
    '킴킴리보진준': '/b/kimkimlee',
    '얼터너티브걸즈': '/b/alterna',
    '아니야': '/b/aniya',
    '트위치': '/b/stream',
    '붕괴학원2': '/b/honkaigakuen',
    '서지수': '/b/seojisoo',
    '거스트': '/b/gust',
    '방갤 대피소': '/b/bang',
    '던만추': '/b/12doe',
    '씹덕대피소': '/b/daepi',
    '잼민이 수용소': '/b/suyongso',
    '원샷': '/b/oneshot',
    '엘소드': '/b/elsword',
    '마마마': '/b/madoka',
    '레이시티': '/b/raycity',
    '마루야마 아야': '/b/maruyamaaya',
    '팔콤': '/b/falcom',
    '서양문화': '/b/western',
    '로마': '/b/spqr',
    '포르자': '/b/forza',
    '오토기프론티어': '/b/otogi',
    '와일드 리프트': '/b/wildrift',
    '비주얼스쿼드': '/b/visualsquad',
    '컴파스': '/b/namulivebtagame',
    'FC 바르셀로나': '/b/barca',
    '페르소나 시리즈': '/b/persona',
    '엘사': '/b/elsa',
    '페르시아': '/b/persia',
    'AFKArena': '/b/afkarena',
    '니쥬': '/b/niziulive',
    '지구': '/b/earths',
    '망할게임': '/b/cusogame',
    '공의경계': '/b/kyoukai',
    '고급카페': '/b/cosycafe',
    '스타 시티즌': '/b/starcitizen',
    '공습하겠습니다': '/b/dcyg',
    'Quaver': '/b/quaver',
    '오컬트': '/b/occult',
    'SFF': '/b/sffpc',
    '파라독스': '/b/paradoxinteractive',
    '마이 리틀 포니': '/b/heroesofthestorm',
    '패러독스 인터랙티브': '/b/paradoxchannel',
    '길잃은 바이킹': '/b/lostvikings',
    'GTS 게임': '/b/shrinkgts',
    '관심종자': '/b/sexwithme',
    '시트러스 테일즈': '/b/citrustales',
    '슬기': '/b/seulgi',
    '인디 게임 개발': '/b/indiegamedev',
    '군인': '/b/soldier',
    '메이플 리부트': '/b/maplereboot',
    '하로프로젝트': '/b/helloproject1998',
    '마루': '/b/maru',
    'skt': '/b/skt1',
    'SMcat채널': '/b/smcat',
    '우크라이나 일기': '/b/ukraine',
    '새티스팩토리': '/b/satisfactory',
    '해병대': '/b/marinecorps',
    '전자여친': '/b/pygmalion',
    '톨키니스트': '/b/jrrtolkien',
    '만년필': '/b/fountainpenlove',
    '사탄드립': '/b/satandlip',
    '갈매기': '/b/seagull',
    '댄싱시티 게임': '/b/dancingcityproject',
    '협동전': '/b/jungkong',
    'yunkido': '/b/kido',
    '메이플스토리2': '/b/maplestory2',
    '크루세이더 킹즈': '/b/crusaderkings',
    '워프레임': '/b/warframe',
    '정신승리': '/b/burningsun',
    '일본 여성성우': '/b/nihonseiyuu',
    '애옹': '/b/meow',
    '팩토리오': '/b/factorio',
    'wyvern': '/b/cretien',
    '페코린느': '/b/pecorine',
    '클리앙대피소': '/b/cliang12',
    '천진반': '/b/tenshinhan733',
    '알파고': '/b/alphago',
    '비트멕스': '/b/bitmex',
    '리브': '/b/livliv',
    '폴 가이즈': '/b/fallguys',
    '남성 건강': '/b/manpower',
    '칸코레': '/b/kancolle',
    '내면의평화': '/b/innerpeace',
    '기동전희': '/b/arterygear',
    '판갤': '/b/fangal',
    '8/15 광복절': '/b/koreagod',
    '자체평점': '/b/ilovesoccer',
    '고민글': '/b/gomin',
    '구미호': '/b/foxspirit',
    '여성형 수인채널': '/b/kemono',
    '여성수인': '/b/anthro',
    '시노앨리스': '/b/sinoalice',
    '마이너취향': '/b/minortaste',
    '피부과': '/b/skin',
    '아무영상': '/b/videos',
    '슈라': '/b/syura',
    '미치쿠사야': '/b/michikusaya1',
    '움짤': '/b/umcal',
    'AA아스키아트 채널': '/b/asukiato',
    '특촬': '/b/tokusatsu',
    '파스텔톤': '/b/pastel',
    '구름도시 이야기': '/b/cloudcity',
    '아이즈원 김민주': '/b/izoneminju',
    '김채원': '/b/kimchaewon',
    '카이저 라이히': '/b/kaiserreich',
    '아이린': '/b/eidk',
    '임시다키': '/b/daki1',
    '후루요니': '/b/furuyoni',
    '레드벨벳': '/b/redvelvet',
    '웬디': '/b/wendy',
    '아르테니아': '/b/artenia',
    '유루드라실': '/b/yurudora',
    '페이커': '/b/faker',
    '린시아다사랑': '/b/dasarang',
    '푸른 성십자회': '/b/stbco',
    '역내청': '/b/oregairu',
    '영웅서기': '/b/heroeslore',
    '첼시': '/b/chelsea',
    '대난투': '/b/smashbros',
    '유저스크립트': '/b/userscript',
    '악어 크루': '/b/dkrdjzmfn',
    '삼성 갤럭시': '/b/samsunggalaxy',
    '협동조합': '/b/coop',
    '케모미미': '/b/kemomimi',
    '유타주': '/b/peopleofutah',
    '상태변화/축소': '/b/transform',
    '질문채널': '/b/questions',
    '우주전쟁': '/b/starcraft2',
    '포도': '/b/grape',
    'C언어': '/b/tcpl',
    '어몽어스': '/b/among',
    '대항해시대2': '/b/bigsailera',
    '스타오션': '/b/starocean',
    '인어': '/b/mermaid',
    'picok12의 개인': '/b/picok12',
    '방귀대장뿡뿡이': '/b/fartlove',
    '노무현 전 대통령': '/b/hewaspresident',
    '텍스트 어드벤처': '/b/textadventure',
    '파티마': '/b/fatima',
    '팀포트리스2': '/b/teamfortress2',
    '아카 잡담': '/b/arcatalk',
    '건담': '/b/gundam',
    '포스트 아포칼립스': '/b/postapocalypse',
    '미니 게임 동아리': '/b/mini',
    '발바닥': '/b/feet',
    '애널': '/b/anal',
    '누타쿠넷': '/b/nutaku',
    '이상': '/b/sanchonyeojeong',
    '포르자 호라이즌': '/b/forzahorizon',
    '카트라이더 러쉬 플러스': '/b/kartrushplus',
    '세븐나이츠': '/b/sevenknights',
    '협동전 이야기': '/b/makeyourstory',
    '원신 아카식 레코드': '/b/genshinbackup',
    '모여봐요 동물의 숲': '/b/acnewhorizons',
    '의과대학': '/b/medicine2',
    '슈퍼전대': '/b/sentai',
    '일본어 번역': '/b/nihonyaku',
    '사이게임즈': '/b/cygames',
  };

  @override
  bool accept(String name) {
    return ['아카라이브', '남라', '아라', 'arcalive', 'namulive']
        .contains(name.replaceAll('.', ''));
  }

  @override
  List<BoardInfo> getLists() {
    var result = List<BoardInfo>();

    result.addAll(boards.entries
        .map((e) => BoardInfo(
              url: 'https://arca.live' + e.value,
              name: e.key,
              // extrainfo: {'mode': 'best'},
              extrainfo: {},
              extractor: 'arcalive',
            ))
        .toList());

    return result;
  }

  @override
  List<String> searchs() {
    // var rr = new List<BoardInfo>();

    // var max = 10;

    // boards.forEach((key, value) {
    //   if (rr.length >= max) return;

    //   if (key.contains(token))
    //     rr.add(BoardInfo(
    //       url: 'https://arca.live' + value,
    //       name: key,
    //       // extrainfo: {'mode': 'best'},
    //       extrainfo: {},
    //       extractor: 'arcalive',
    //     ));
    // });

    var rr = List<String>();

    boards.forEach((key, value) {
      // print(key);
      rr.add(key);
    });

    return rr;
  }

  @override
  BoardInfo getBoardFromName(String name) {
    return BoardInfo(
      url: 'https://arca.live' + boards[name],
      name: name,
      // extrainfo: {'mode': 'best'},
      extrainfo: {},
      extractor: 'arcalive',
    );
  }

  @override
  List<String> extraOptions() {
    return ['헤드라인|1|mode|best'];
  }

  @override
  Future<bool> supportClass(String html) async {
    var doc = parse(html);
    var categories = doc.querySelector(
        'html > body > div:nth-of-type(1) > div:nth-of-type(3) > article:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(4) > div:nth-of-type(1) > div:nth-of-type(1) > ul:nth-of-type(1) > li:nth-of-type(1) > a:nth-of-type(1)');
    return categories != null;
  }

  @override
  Future<List<String>> getClasses(String html) async {
    var doc = parse(html);
    var categories = doc.querySelector(
        'html > body > div:nth-of-type(1) > div:nth-of-type(3) > article:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(4) > div:nth-of-type(1) > div:nth-of-type(1) > ul:nth-of-type(1)');
    return categories
        .querySelectorAll('li')
        .map((e) => '${e.text.trim()}|category|${e.text.trim()}')
        .toList();
  }
}
